// REST routes for file transfers
// POST /api/files/upload         — upload a file (multipart)
// GET  /api/files/download/:id   — download a file by transfer ID
// GET  /api/files/history/:userId — get transfer history for a user

import { Router, Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import { prisma } from '../db/prisma';
import { upload, uploadDir } from '../middleware/upload';

export const filesRouter = Router();

// Upload a file and record the transfer in the database
// Expected form fields: senderId, receiverId, transferId (pre-generated by client)
filesRouter.post('/upload', upload.single('file'), async (req: Request, res: Response) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file provided' });
    }

    const { senderId, receiverId, transferId } = req.body;
    if (!senderId || !receiverId || !transferId) {
      // Clean up orphaned file
      fs.unlinkSync(req.file.path);
      return res.status(400).json({ error: 'Missing senderId, receiverId, or transferId' });
    }

    // Upsert transfer record (may have been pre-created by socket notification)
    const transfer = await prisma.transfer.upsert({
      where: { id: transferId },
      create: {
        id: transferId,
        filename: req.file.originalname,
        mimeType: req.file.mimetype,
        sizeBytes: BigInt(req.file.size),
        storagePath: req.file.path,
        status: 'COMPLETED',
        completedAt: new Date(),
        senderId,
        receiverId,
      },
      update: {
        storagePath: req.file.path,
        status: 'COMPLETED',
        completedAt: new Date(),
      },
    });

    const downloadUrl = `/api/files/download/${transfer.id}`;
    res.json({ transferId: transfer.id, downloadUrl, filename: req.file.originalname });
  } catch (err) {
    console.error('Upload error:', err);
    res.status(500).json({ error: 'Upload failed' });
  }
});

// Stream a file to the client for download
filesRouter.get('/download/:id', async (req: Request, res: Response) => {
  try {
    const transfer = await prisma.transfer.findUnique({ where: { id: req.params.id } });
    if (!transfer) return res.status(404).json({ error: 'Transfer not found' });

    if (!fs.existsSync(transfer.storagePath)) {
      return res.status(404).json({ error: 'File no longer available on disk' });
    }

    res.setHeader('Content-Disposition', `attachment; filename="${transfer.filename}"`);
    res.setHeader('Content-Type', transfer.mimeType);
    res.setHeader('Content-Length', transfer.sizeBytes.toString());
    fs.createReadStream(transfer.storagePath).pipe(res);
  } catch (err) {
    res.status(500).json({ error: 'Download failed' });
  }
});

// Get transfer history between two users
filesRouter.get('/history/:userId', async (req: Request, res: Response) => {
  try {
    const transfers = await prisma.transfer.findMany({
      where: {
        OR: [{ senderId: req.params.userId }, { receiverId: req.params.userId }],
        status: 'COMPLETED',
      },
      orderBy: { createdAt: 'desc' },
      take: 50,
      include: {
        sender: { select: { id: true, username: true } },
        receiver: { select: { id: true, username: true } },
      },
    });
    // Convert BigInt to number for JSON serialization
    res.json(
      transfers.map((t) => ({ ...t, sizeBytes: Number(t.sizeBytes) })),
    );
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch history' });
  }
});
